version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: nl2sql-neo4j
    environment:
      NEO4J_AUTH: "neo4j/DevGraph123!"   # >=8 chars
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_server_config_strict__validation_enabled: "false"
      NEO4J_dbms_security_auth__enabled: "true"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    restart: unless-stopped

  dev:
    image: natural-language-sql-dev:latest
    build:
      context: .
      podmanfile: Containerfile
    volumes:
      - .:/app:Z
    tty: true
    stdin_open: true
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: "DevGraph123!"     # must match NEO4J_AUTH
      ARTIFACTS_DIR: /app/out
      ORIGINALS_KEYWORDS: /app/keywords_and_functions.yaml
      ORIGINALS_SCHEMA: /app/schema.yaml
    depends_on:
      - neo4j
    command: /bin/bash

volumes:
  neo4j-data: {}
  neo4j-logs: {}
